FROM debian:bookworm

# Install systemd and required packages
RUN apt-get update && apt-get install -y \
    systemd \
    systemd-sysv \
    openssh-client \
    sqlite3 \
    curl \
    jq \
    ca-certificates \
    openssl

# Remove unnecessary systemd services to speed up boot
RUN systemctl mask \
    systemd-resolved.service \
    systemd-networkd.service \
    systemd-timesyncd.service

COPY systemd/sshcad-sysusers.conf /usr/lib/sysusers.d/sshcad.conf
RUN systemd-sysusers

RUN mkdir -p /var/lib/sshcad /etc/sshcad /etc/credstore.encrypted
RUN chown sshcad:sshcad /var/lib/sshcad

COPY --chmod=755 sshcad /usr/local/bin/sshcad
COPY systemd/sshcad.service /etc/systemd/system/sshcad.service
COPY trees/test/ /

RUN systemctl enable sshcad-test-setup.service sshcad.service

# For debugging
RUN echo "root:hunter2" | chpasswd

CMD ["/lib/systemd/systemd"]
